replicaCount: 1

namespace: dev

image: the_image
imageTag: the_tag
imagePullPolicy: Always

global:
  imagePullSecrets:
    - regcred       # regcred = kubectl secret name - # https://kubernetes.io/docs/tasks/configure-pod-container/pull-image-private-registry/