apiVersion: apps/v1
kind: Deployment
metadata:
  name: catalog
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: catalog-service
      release: {{ .Values.imageTag }}
  template:
    metadata:
      labels:
        app: catalog-service
        release: {{ .Values.imageTag }}
      annotations:
        owner: Team Services
        chat-channel: dev-team-services 
    spec:
      containers:
      - name: catalog
        image: "{{ .Values.image }}:{{ .Values.imageTag }}"
        imagePullPolicy:  {{ .Values.imagePullPolicy }}
        ports:
        - containerPort: 8080
          name: catalog
        env:
        - name: DT_CUSTOM_PROP
          value: "project=dt-orders service=catalog-service"