apiVersion: apps/v1
kind: Deployment
metadata:
  name: catalog
  namespace: {{ .Values.namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/part-of: dt-orders
      app.kubernetes.io/name: catalog-service
    spec:
      containers:
      - name: catalog
        image: "{{ .Values.image }}:{{ .Values.imageTag }}"
        imagePullPolicy:  {{ .Values.imagePullPolicy }}
        ports:
        - containerPort: 8080
          name: catalog
        env:
        - name: DT_CUSTOM_PROP
          value: "project=dt-orders service=catalog-service"