apiVersion: apps/v1
kind: Deployment
metadata:
  name: catalog
  namespace: {{ .Values.namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/part-of: dt-orders
      app.kubernetes.io/name: catalog-service
  template:
    metadata:
      labels:
        app.kubernetes.io/name: "catalog-service"
        app.kubernetes.io/version: {{ .Values.imageTag }}
        app.kubernetes.io/component: "service"
        app.kubernetes.io/part-of: "dt-orders"
        app.kubernetes.io/managed-by: "helm"
        app.kubernetes.io/created-by: "dynatrace-demos"
      annotations:
        owner: Team Services
        chat-channel: dev-team-services 

    spec:
      containers:
      - name: catalog
        image: "{{ .Values.image }}:{{ .Values.imageTag }}"
        imagePullPolicy:  {{ .Values.image.pullPolicy }}
        ports:
        - containerPort: 8080
          name: catalog
        env:
        - name: DT_CUSTOM_PROP
          value: "project=dt-orders service=catalog-service"