apiVersion: v1
kind: Service
metadata:
  name: catalog
  labels:
    app.kubernetes.io/part-of: dt-orders
    app.kubernetes.io/name: catalog-service
spec:
  ports:
    - port: 8080
      targetPort: 8080
      name: catalog
  selector:
    app.kubernetes.io/part-of: dt-orders
    app.kubernetes.io/name: catalog-service
  type: ClusterIP