apiVersion: v1
kind: Service
metadata:
  name: catalog
  namespace: {{ .Values.namespace }}
  labels:
    app: catalog-service
    part-of: dt-orders
spec:
  ports:
    - port: 8080
      targetPort: 8080
      name: catalog
  selector:
    app: catalog-service
    part-of: dt-orders
  type: LoadBalancer