resources:
  - name: github
    type: GitRepo
    configuration:
      gitProvider: githubIntegration                      # Name of GitHub integration, which provides connectivity to GitHub repo
      path: dt-demos/jfrog-pipelines-dynatrace-example    # GitHub Repo path, if path is modified, change the resource name as well
      branches:
        include: main
      buildOn:
        commit: true
  
  - name: simpleDockerImage
    type: Image
    configuration:
      registry: artifactoryIntegration                                    # Name of Docker integration in Artifactory instance
      sourceRepository: default-docker-local                              # Docker repository name
      imageName: dynatracedemos.jfrog.io/art-docker-dynatrace/busybox     # Docker image name
      imageTag: ${run_number}

  - name: simpleBuildInfo
    type: BuildInfo
    configuration:
      sourceArtifactory: artifactoryIntegration         # Your Artifactory integration
      buildName: SampleApp                              # The name of the application image
      buildNumber: ${run_number}

  - name: simpleHelmChartBuildInfo
    type: BuildInfo
    configuration:
      sourceArtifactory: artifactoryIntegration         # Your Artifactory integration
      buildName: SampleApp                              # The name of the application Helm chart
      buildNumber: '0.1.${run_number}'                  # Starting build number, the following will be 0.0.1

  - name: simplehelmRepoChart
    type: GitRepo
    configuration:
      gitProvider: githubIntegration  # Name of GitHub integration, which provides connectivity to GitHub repo
      path: dt-demos/jfrog-pipelines-dynatrace-example            # GitHub Repo path
      branches:
        include: main
      buildOn:
        commit: true

  - name: simplehelmChart
    type: HelmChart
    configuration:
      sourceArtifactory: artifactoryIntegration       # Your Artifactory integration
      repository: simplecharts                        # Helm chart repository in your Artifactory instance
      chart: busybox                                  # The name of the Helm chart
      version: 0.1.0                                  

pipelines:
  - name: dynatraceDemo
    configuration:
      environmentVariables:
        readOnly:
          my_releaseName: "busybox"
    steps:
      - name: DockerBuild
        type: DockerBuild
        configuration:
          affinityGroup: buildAndPush
          integrations:
            - name: artifactoryIntegration
          inputResources:
            - name: github
          dockerFileLocation: pipeline/dynatrace/       # Relative location of the Dockerfile in the GitHub repo
          dockerFileName: Dockerfile
          dockerImageName: dynatracedemos.jfrog.io/art-docker-dynatrace/busybox
          dockerImageTag: ${run_number}

      - name: DockerPush
        type: DockerPush
        configuration:
          affinityGroup: buildAndPush
          autoPublishBuildInfo: true
          integrations:
            - name: artifactoryIntegration                  # Your Artifactory integration
          targetRepository: art-docker-dynatrace            # Docker repository, where the image will be pushed
          inputSteps:
            - name: DockerBuild
          outputResources:
            - name: simpleBuildInfo                         # Build info updated after the step execution
            - name: simpleDockerImage                       # Docker image resource, created after the step execution

      - name: HelmPublish
        type: HelmPublish
        configuration:
          helmVersion: 3                                    # Use Helm version 3 to build the Helm chart
          chartPath: pipeline/dynatrace/busybox/
          affinityGroup: helm_install
          inputSteps:
            - name: DockerPush
          inputResources:
            - name: simplehelmRepoChart
              trigger: false
          outputResources:
            - name: simplehelmChart                        # Helm chart will be created and pushed to the repo, declared in simplehelmChart resource
            - name: simpleHelmChartBuildInfo
        execution:
          onStart:
            - printenv
          onFailure:
            - echo "Failure"

      - name: HelmDeploy
        type: HelmDeploy
        configuration:
          helmVersion: 3
          affinityGroup: helm_install
          releaseName: busybox${run_number}
          integrations:
            - name: k8sIntegration
          inputResources:
            - name: simplehelmChart
            - name: simpleDockerImage
          inputSteps:
            - name: HelmPublish
          valueFilePaths:
            - values.yaml
        execution:
          onStart:
            - kubectl config current-context
            - add_run_variables CLUSTER="$(kubectl config current-context)"
            - add_run_variables RELEASE_NAME="${my_releaseName}"
            - printenv
          onSuccess:
            - kubectl get pods
          onFailure:
            - echo "Failure"

      - name: modifyHelmChartProperties
        type: Bash
        configuration:
          affinityGroup: helm_install
          integrations:
            - name: artifactoryIntegration
          inputResources:
            - name: simplehelmChart
          inputSteps:
            - name: HelmDeploy
        execution:
          onExecute:
            - printenv
            - echo "Modifying helm chart properties"
            - echo "${int_artifactoryIntegration_url}/api/storage/simplecharts/busybox-${res_simplehelmChart_version}.tgz"
            - echo "deployedOnCluster=${CLUSTER}"
            - echo "helmInstallationName=${RELEASE_NAME}"
            - echo "deploymentTimestamp=${TIME}"
            - echo "Set current time as a deployment time"
            - TIME=$(date +%s)
            - curl -v --location --request PUT "${int_artifactoryIntegration_url}/api/storage/simplecharts/busybox-${res_simplehelmChart_version}.tgz?properties=deployedOnCluster=${CLUSTER}%7ChelmInstallationName=${RELEASE_NAME}%7CdeploymentTimestamp=${TIME}" --header "Accept:application/json" --header "X-Jfrog-Art-Api:${int_artifactoryIntegration_apikey}"
          onFailure:
            - echo "Failure"

      - name: Dynatrace_deployment_event
        type: Bash
        configuration:
          affinityGroup: helm_install
          integrations:
            - name: artifactoryIntegration
            - name: dynatraceIntegration
          inputResources:
            - name: github
            - name: simplehelmChart
          inputSteps:
            - name: modifyHelmChartProperties
        execution:
          onStart:
            - echo "Preparing for work..."
          onExecute:
            - printenv
            - JSONOutput=$(curl --location --request GET "${int_artifactoryIntegration_url}/api/storage/simplecharts/busybox-${res_simplehelmChart_aa_version}.tgz?properties=helmInstallationName,chart.version,deployedOnCluster,vcs.url" --header "Accept:application/json" --header "X-Jfrog-Art-Api:${int_artifactoryIntegration_apikey}" | jq .)
            - echo $JSONOutput
            - ChartVersion=$(echo $JSONOutput | jq '.properties."chart.version"[0]')
            - HelmInstallationName=$(echo $JSONOutput | jq '.properties.helmInstallationName[0]')
            - VCS_URL=$(echo $JSONOutput | jq '.properties."vcs.url"[0]')
            - DeployedOnCluster=$(echo $JSONOutput | jq '.properties.deployedOnCluster[0]')
            - curl -H 'Content-Type:application/json' --location --request POST "https://${int_dynatraceIntegration_DT_URL}.live.dynatrace.com/api/v1/events"  -H 'Accept:application/json' -HAuthorization:"Api-Token ${int_dynatraceIntegration_DT_API_TOKEN}" -d "{\"eventType\":\"CUSTOM_DEPLOYMENT\",\"attachRules\":{\"tagRule\":{\"meTypes\":\"SERVICE\",\"tags\":[{\"context\":\"CONTEXTLESS\",\"key\":\"JFrog\",\"value\":\"busybox\"}]}},\"deploymentName\":\"RuntimeDeployment\",\"deploymentVersion\":\"${res_simplehelmChart_aa_version}\",\"deploymentProject\":\"BusyBox-nginx\",\"source\":\"${int_artifactoryIntegration_url}\",\"customProperties\":{\"ChartVersion\":${ChartVersion},\"JFrogArtifactoryUrl\":\"${int_artifactoryIntegration_url}\",\"HelmInstallationName\":${HelmInstallationName},\"RunNumber\":\"${run_number}\",\"DeployedOnCluster\":${DeployedOnCluster},\"VCS_URL\":${VCS_URL},\"DockerImageName\":\"${build_image_dockerImageName}\"}}"
          onSuccess:
            - echo ""
          onFailure:
            - echo "Failure"  