targetRepository: "default-docker-local"
sourceRepository: "default-docker-local"
imageName: "dynatracedemos.jfrog.io/art-docker-dynatrace/busybox"
gitProvider: "githubIntegration"
repoPath: "dt-demos/jfrog-pipelines-dynatrace-example"